// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nprqxzybpkllstfrivlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wcnF4enlicGtsbHN0ZnJpdmx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzUzNzUsImV4cCI6MjA3MDI1MTM3NX0.lBF_HP5UCkQi5u5oRFgI5vrTsi7cLxyf28MDJ4XmE2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});